### ISSUE TITLE
example 37: couldn't connect

### ISSUE THREAD

**Issue by zipperer** [blakemcbride/Dynace#8]
In repository
```
$ cd Dynace/examples/exam37
$ make
$ ./main
Couldn't connect
```
It looks like either or both of `http://192.168.202.67:3490/` and `blake.florida-software.com:3490` are not listening for connections. 

Environment: same as #6

**Comment by blakemcbride** [comment]
This is basically a documentation issue.  The URL and IP address are specific to the environment its being used in.  I updated the documentation.  Thanks!

**Comment by blakemcbride** [comment]
I corrected the readme and code.
