### ISSUE TITLE
example 38: error: runtime: segmentation fault

### ISSUE THREAD

**Issue by zipperer** [blakemcbride/Dynace#9]
In repository
```
$ cd Dynace/examples/exam38
$ make
$ ./main
Line start                                                                                            
Regular code                                                                                          
Segmentation fault: 11
```

Environment: same as #6 .

**Comment by blakemcbride** [comment]
This has been corrected.  Turns out, example 38 was attempting to demonstrate a try/catch facility which the signal code is not.  I corrected the example to correctly exercise the signal handling ability.
